"use client";

import { useEffect, useState } from "react";
import { GraduationCap, Loader2, ChevronDown, ChevronUp, Beaker, FileText, Code, Users } from "lucide-react";
import { apiFetch } from "@/lib/api-client";
import { useRequireAuth } from "@/hooks/use-require-auth";
import { format } from "date-fns";

interface InterviewSession {
  id: string;
  application_id: string;
  professor_name: string;
  university: string;
  lab_questions: string[];
  paper_questions: string[];
  technical_questions: string[];
  hr_questions: string[];
  created_at: string | null;
}

export default function InterviewPage() {
  const { checked } = useRequireAuth();
  const [sessions, setSessions] = useState<InterviewSession[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    apiFetch<InterviewSession[]>("/interviews")
      .then((data) => {
        if (!cancelled) {
          setSessions(data || []);
          if (data && data.length > 0) setExpandedId(data[0].id);
          setLoading(false);
        }
      })
      .catch(() => {
        if (!cancelled) setLoading(false);
      });
    return () => { cancelled = true; };
  }, []);

  if (!checked) return null;

  return (
    <div className="max-w-[900px] mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-ink-900 flex items-center gap-2">
          <GraduationCap size={24} className="text-brand-500" />
          Interview Coach
        </h1>
        <p className="text-sm text-ink-500 mt-1">
          Review tailored interview questions generated by the AI for your applications.
        </p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-20 text-ink-400">
          <Loader2 className="w-8 h-8 animate-spin" />
        </div>
      ) : sessions.length === 0 ? (
        <div className="text-center py-20 bg-white rounded-xl border border-ink-100 shadow-sm">
          <GraduationCap className="w-12 h-12 text-ink-300 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-ink-900">No Sessions Found</h3>
          <p className="text-ink-500 mt-1">Run an application pipeline to generate interview prep materials.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {sessions.map((session) => {
            const isExpanded = expandedId === session.id;
            return (
              <div key={session.id} className="bg-white rounded-xl border border-ink-100 shadow-sm overflow-hidden">
                <button
                  onClick={() => setExpandedId(isExpanded ? null : session.id)}
                  className="w-full p-5 flex items-center justify-between text-left hover:bg-ink-50 transition-colors"
                >
                  <div>
                    <h3 className="font-semibold text-ink-900 text-lg">
                      {session.professor_name} <span className="font-normal text-ink-500 text-base">at {session.university}</span>
                    </h3>
                    {session.created_at && (
                      <p className="text-sm text-ink-400 mt-1">
                        Generated on {format(new Date(session.created_at), "MMMM d, yyyy")}
                      </p>
                    )}
                  </div>
                  <div className="text-ink-400">
                    {isExpanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                  </div>
                </button>

                {isExpanded && (
                  <div className="p-5 pt-0 border-t border-ink-100">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-5">
                      
                      {/* Lab Questions */}
                      <div className="bg-brand-50/50 rounded-xl p-4 border border-brand-100">
                        <h4 className="font-medium text-brand-900 flex items-center gap-2 mb-3">
                          <Beaker size={18} className="text-brand-500" /> Lab & Research Fit
                        </h4>
                        <ul className="space-y-3">
                          {session.lab_questions?.map((q, i) => (
                            <li key={i} className="text-sm text-ink-700 leading-relaxed">• {q}</li>
                          ))}
                          {(!session.lab_questions || session.lab_questions.length === 0) && (
                            <li className="text-sm text-ink-400 italic">No questions generated.</li>
                          )}
                        </ul>
                      </div>

                      {/* Paper Questions */}
                      <div className="bg-blue-50/50 rounded-xl p-4 border border-blue-100">
                        <h4 className="font-medium text-blue-900 flex items-center gap-2 mb-3">
                          <FileText size={18} className="text-blue-500" /> Recent Publications
                        </h4>
                        <ul className="space-y-3">
                          {session.paper_questions?.map((q, i) => (
                            <li key={i} className="text-sm text-ink-700 leading-relaxed">• {q}</li>
                          ))}
                          {(!session.paper_questions || session.paper_questions.length === 0) && (
                            <li className="text-sm text-ink-400 italic">No questions generated.</li>
                          )}
                        </ul>
                      </div>

                      {/* Technical Questions */}
                      <div className="bg-violet-50/50 rounded-xl p-4 border border-violet-100">
                        <h4 className="font-medium text-violet-900 flex items-center gap-2 mb-3">
                          <Code size={18} className="text-violet-500" /> Technical Assessment
                        </h4>
                        <ul className="space-y-3">
                          {session.technical_questions?.map((q, i) => (
                            <li key={i} className="text-sm text-ink-700 leading-relaxed">• {q}</li>
                          ))}
                          {(!session.technical_questions || session.technical_questions.length === 0) && (
                            <li className="text-sm text-ink-400 italic">No questions generated.</li>
                          )}
                        </ul>
                      </div>

                      {/* HR Questions */}
                      <div className="bg-amber-50/50 rounded-xl p-4 border border-amber-100">
                        <h4 className="font-medium text-amber-900 flex items-center gap-2 mb-3">
                          <Users size={18} className="text-amber-500" /> Behavioral & HR
                        </h4>
                        <ul className="space-y-3">
                          {session.hr_questions?.map((q, i) => (
                            <li key={i} className="text-sm text-ink-700 leading-relaxed">• {q}</li>
                          ))}
                          {(!session.hr_questions || session.hr_questions.length === 0) && (
                            <li className="text-sm text-ink-400 italic">No questions generated.</li>
                          )}
                        </ul>
                      </div>

                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
